# Generated by Django 3.0.5 on 2020-04-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdiatapais', models.CharField(max_length=4)),
                ('cdsiscomexpais', models.CharField(max_length=4)),
                ('nomepais', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=3)),
            ],
        ),
    ]
